Aliasy do pokazania innym graczom swojego zmęczenia/obciązenia/many etc.
tjurczyk/arkadia pull request #836
Opened 2021-01-08 22:30 UTC by mjamro

Niektóre statystyki postaci nie są widoczne z zewnątrz - np. poziom zmęczenia, obciązenia, głodu, 
pragnienia, upicie czy many. Aby ułatwić przekazywanie tych wartości innym graczom została dodana komenda
`/zamelduj <co>` która uruchamia prekonfigurowane komendy mające za zadanie poinformować innych o stanie twojej postaci. 

Przykładowo:

```
> /zamelduj zmeczenie
Mowisz: Troche zmeczony.
```

lub w skróconej formie:

```
> /zamzme
Mowisz: Troche zmeczony.
```

Analogiczne komendy zostały dodane dla pozostałych statystyk:

* `/zamelduj zmeczenie` lub `/zamzme`
* `/zamelduj obciazenie` lub `/zamobc`
* `/zamelduj mane` lub `/zamman`
* `/zamelduj glod` lub `/zamglo`
* `/zamelduj pragnienie` lub `/zampra`
* `/zamelduj upicie` lub `/zamupi`

Bieżąca wartość stystyki brana jest z automatycznie z GMCP. 

Komendy do wysłania ustawiane są w pliku konfiguracji postaci i mają formę listy komend. Za każdym kolejnym wywołaniem wysyłana jest kolejna komenda z tej listy. Ustawienia przyjmują osobne wartości w formie męskiej i żeńskiej, tak by domyślne  działały dla postaci obu płci (różna odmiana) oraz by łatwo można było przenosić ustawienia pomiędzy postaciami. Zawsze używana jest tylko wartość pasująca do płci otrzymanej z GMCP.

Jeżeli chcesz wysłać więcej niż jedną komendę na raz musisz podać je jako jedną wartość i oddzielić znakiem separatora komend (najczęsciej `;`)

Przykładowo dla konfiguracji:

```json
"scripts.character.state_reporting.fatigue.options_male.0": [
    "usmiechnij sie dumnie;'W pelni wypoczety.", 
    "machnij reka lekko;'W pelni sil."
],
```

użycie będzie wyglądało następująco:

```
/zamzme
Usmiechasz sie dumnie.
Mowisz: W pelni wypoczety.
/zamzme
Machasz reka lekko.
Mowisz: W pelni sil.
/zamzme                  
Usmiechasz sie dumnie.
Mowisz: W pelni wypoczety.
```

2021-01-21 08:13 UTC, tjurczyk commented on config.md
> +## `scripts.character.state_reporting.<cecha>.<wartosc_liczbowa>`
Czy idea jest ze maja byc to konfigurowalne wartosci? Jesli tak, to nie ma tego w configu

2021-02-25 07:43 UTC, felixd commented
A co w przypadku gdy GMCP nie zwróci akurat danej informacji o statusie postaci? Załóżmy, że chcę teraz sprawdzić zmęczenie.

```
Jestes zmeczony.
Jestes w zlej kondycji.
lua display(gmcp.char.state)
{
  hp = 2
}
```

2021-02-25 12:33 UTC, Delwing commented
@felixd słusznie zauważone. Zamiast wysyłać request o aktualizacje, lepiej trzymać "pełną" tablicę zupełnie oddzielnie i aktualizować wartości tak jak przychodzą komunikaty gmcp (czy to pełne czy częsciowe) - a wysłać żądanie o aktualizacje tylko jeżeli z jakiegoś powodu nie mamy danej wartości przed wypowiedzeniem komunikatu.

2021-02-25 22:04 UTC, mjamro commented
> @felixd słusznie zauważone. Zamiast wysyłać request o aktualizacje, lepiej trzymać "pełną" tablicę zupełnie oddzielnie i aktualizować wartości tak jak przychodzą komunikaty gmcp (czy to pełne czy częsciowe) - a wysłać żądanie o aktualizacje tylko jeżeli z jakiegoś powodu nie mamy danej wartości przed wypowiedzeniem komunikatu.

A nie wystarczy użyć `scripts.character.state` które ma ostatni otrzymany stan wszystkich  atrybutów?

2021-02-26 01:13 UTC, Delwing commented
Wystarczy.

2021-07-08 08:57 UTC, Delwing requested changes
Właśnie zdałem sobie sprawę, że moje komentarze nie są nawet widoczne dopóki nie kliknę submit review.

2021-07-08 08:59 UTC, Delwing commented on skrypty/character/state_reporting.lua
> +            ["0"] = {"'W pelni wypoczety.", "'W pelni sil."},
Chociaż z drugiej strony będzie zgodne z tym co Arkadia wysyła.

2021-09-08 09:27 UTC, Delwing commented
W związku z brakiem aktywności w PR i poprawek zamykam.

2021-09-08 09:27 UTC, closed without merging